<?php
require_once __DIR__.'/includes/db.php';
function setup_start($title){echo '<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><body style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Arial,sans-serif;max-width:760px;margin:32px auto;padding:16px;line-height:1.45"><h1 style="font-size:34px;line-height:1.05">'.htmlspecialchars($title,ENT_QUOTES,'UTF-8').'</h1>';}
function setup_end(){echo '</body>';}
function setup_pre($text){echo '<pre style="white-space:pre-wrap;word-break:break-word;background:#f3f4f6;padding:12px;border-radius:12px;border:1px solid #e5e7eb">'.htmlspecialchars($text,ENT_QUOTES,'UTF-8').'</pre>';}
function table_exists($table){$row=one("SELECT COUNT(*) AS c FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?",[$table]);return ((int)($row['c']??0))>0;}
function split_sql($sql){$out=[];$buf='';$inS=false;$inD=false;$esc=false;$len=strlen($sql);for($i=0;$i<$len;$i++){ $ch=$sql[$i];$buf.=$ch;if($esc){$esc=false;continue;}if($ch==='\\'){$esc=true;continue;}if($ch==="'"&&!$inD){$inS=!$inS;continue;}if($ch==='"'&&!$inS){$inD=!$inD;continue;}if($ch===';'&&!$inS&&!$inD){$t=trim($buf);if($t!==''&&$t!==';')$out[]=$t;$buf='';}}$t=trim($buf);if($t!=='')$out[]=$t;return $out;}
function run_sql_file($path){if(!file_exists($path))throw new Exception('SQL file not found: '.$path);$count=0;foreach(split_sql(file_get_contents($path)) as $stmt){$clean=trim($stmt);if($clean===''||str_starts_with($clean,'--'))continue;db()->exec($clean);$count++;}return $count;}
try{db()->query('SELECT 1');}catch(Throwable $e){http_response_code(500);setup_start('Database connection failed');echo '<p>The setup file loaded, but it could not connect to MySQL.</p>';echo '<p>Check .env at:</p>';setup_pre('/public_html/.env\n/public_html/app/.env');setup_pre($e->getMessage());setup_end();exit;}
$publicRoot=dirname(__DIR__,2);$schemaFile=$publicRoot.'/sql/001_schema.sql';$seedFile=$publicRoot.'/sql/002_seed.sql';
if(!table_exists('admin_users')){if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['install_schema']??'')==='1'){try{$a=run_sql_file($schemaFile);$b=run_sql_file($seedFile);setup_start('Database installed');echo '<p>Schema statements: <strong>'.(int)$a.'</strong></p><p>Seed statements: <strong>'.(int)$b.'</strong></p><p><a href="'.htmlspecialchars(admin_url('setup_admin.php'),ENT_QUOTES,'UTF-8').'">Continue to owner setup</a></p>';setup_end();exit;}catch(Throwable $e){http_response_code(500);setup_start('Database install failed');setup_pre($schemaFile.'\n'.$seedFile);setup_pre($e->getMessage());setup_end();exit;}}setup_start('Database tables missing');echo '<p>MySQL credentials are working, but SPEC-1 tables have not been installed yet.</p><p>This installer will run:</p>';setup_pre($schemaFile.'\n'.$seedFile);echo '<form method="post"><input type="hidden" name="install_schema" value="1"><button style="width:100%;height:52px;border:0;background:#1f6feb;color:#fff;border-radius:14px;font-weight:700;font-size:16px">Install Database Tables</button></form>';setup_end();exit;}
$count=one('SELECT COUNT(*) c FROM admin_users')['c']??0;if($count>0){setup_start('Admin already exists');echo '<p>Delete this file now:</p>';setup_pre('/public_html/app/admin/setup_admin.php');echo '<p><a href="'.htmlspecialchars(admin_url('login.php'),ENT_QUOTES,'UTF-8').'">Go to login</a></p>';setup_end();exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['create_owner']??'')==='1'){$email=$_POST['email']??'';$password=$_POST['password']??'';if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<12){setup_start('Invalid owner credentials');echo '<p>Use a valid email and password of at least 12 characters.</p>';setup_end();exit;}exec_sql("INSERT INTO admin_users (email,password_hash,role,is_active,created_at,updated_at) VALUES (?,?, 'owner',1,NOW(),NOW())",[$email,password_hash($password,PASSWORD_DEFAULT)]);setup_start('Owner created');echo '<p>Owner admin created successfully.</p><p>Delete this file immediately:</p>';setup_pre('/public_html/app/admin/setup_admin.php');echo '<p><a href="'.htmlspecialchars(admin_url('login.php'),ENT_QUOTES,'UTF-8').'">Go to login</a></p>';setup_end();exit;}
setup_start('Create Owner Admin');echo '<p>This creates the first admin account. Delete this file after success.</p><form method="post"><input type="hidden" name="create_owner" value="1"><input name="email" type="email" placeholder="email" style="width:100%;height:48px;margin:8px 0;border:1px solid #d1d5db;border-radius:12px;padding:0 12px;font-size:16px"><input name="password" type="password" placeholder="password, min 12 chars" style="width:100%;height:48px;margin:8px 0;border:1px solid #d1d5db;border-radius:12px;padding:0 12px;font-size:16px"><button style="width:100%;height:52px;border:0;background:#1f6feb;color:#fff;border-radius:14px;font-weight:700;font-size:16px">Create Owner</button></form>';setup_end();
?>
